-- Weeko: fehlende Spalten aller Supabase-Tabellen nachziehen (idempotent).
-- Aus src/db/schema.ts generiert. Einmalig im Supabase SQL-Editor ausfuehren.
-- Bestehende Spalten werden uebersprungen; nur fehlende werden angelegt.

alter table public.profile add column if not exists "user_id" text;
alter table public.profile add column if not exists "height_cm" double precision;
alter table public.profile add column if not exists "age" integer;
alter table public.profile add column if not exists "sex" text;
alter table public.profile add column if not exists "weight_kg" double precision;
alter table public.profile add column if not exists "goal" text;
alter table public.profile add column if not exists "goal_rate_kg_per_week" double precision;
alter table public.profile add column if not exists "nutrition_goals" jsonb;
alter table public.profile add column if not exists "language" text;
alter table public.profile add column if not exists "theme" text;
alter table public.profile add column if not exists "onboarding_done" boolean;
alter table public.profile add column if not exists "updated_at" text;
alter table public.weekly_structure add column if not exists "weekday" integer;
alter table public.weekly_structure add column if not exists "work_start" text;
alter table public.weekly_structure add column if not exists "work_end" text;
alter table public.weekly_structure add column if not exists "work_location" text;
alter table public.weekly_structure add column if not exists "done_by" text;
alter table public.weekly_structure add column if not exists "fixed_blocks" jsonb;
alter table public.weekly_structure add column if not exists "user_id" uuid;
alter table public.weekly_structure add column if not exists "updated_at" text;
alter table public.equipment add column if not exists "name" text;
alter table public.equipment add column if not exists "available" boolean;
alter table public.equipment add column if not exists "user_id" uuid;
alter table public.equipment add column if not exists "updated_at" text;
alter table public.exercise add column if not exists "name" text;
alter table public.exercise add column if not exists "equipment_id" text;
alter table public.exercise add column if not exists "is_weighted" boolean;
alter table public.exercise add column if not exists "notes" text;
alter table public.exercise add column if not exists "slug" text;
alter table public.exercise add column if not exists "muscle_group" text;
alter table public.exercise add column if not exists "user_id" uuid;
alter table public.exercise add column if not exists "updated_at" text;
alter table public.week add column if not exists "year" integer;
alter table public.week add column if not exists "iso_week" integer;
alter table public.week add column if not exists "status" text;
alter table public.week add column if not exists "source" text;
alter table public.week add column if not exists "created_at" text;
alter table public.week add column if not exists "user_id" uuid;
alter table public.week add column if not exists "updated_at" text;
alter table public.block add column if not exists "week_id" text;
alter table public.block add column if not exists "date" text;
alter table public.block add column if not exists "type" text;
alter table public.block add column if not exists "start" text;
alter table public.block add column if not exists "end" text;
alter table public.block add column if not exists "title" text;
alter table public.block add column if not exists "details" jsonb;
alter table public.block add column if not exists "status" text;
alter table public.block add column if not exists "user_id" uuid;
alter table public.block add column if not exists "updated_at" text;
alter table public.task add column if not exists "title" text;
alter table public.task add column if not exists "category" text;
alter table public.task add column if not exists "estimated_minutes" integer;
alter table public.task add column if not exists "recurrence" text;
alter table public.task add column if not exists "status" text;
alter table public.task add column if not exists "window_day" text;
alter table public.task add column if not exists "window_start" text;
alter table public.task add column if not exists "window_end" text;
alter table public.task add column if not exists "context" jsonb;
alter table public.task add column if not exists "block_id" text;
alter table public.task add column if not exists "week_id" text;
alter table public.task add column if not exists "created_at" text;
alter table public.task add column if not exists "completed_at" text;
alter table public.task add column if not exists "user_id" uuid;
alter table public.task add column if not exists "updated_at" text;
alter table public.session_template add column if not exists "key" text;
alter table public.session_template add column if not exists "name_key" text;
alter table public.session_template add column if not exists "items" jsonb;
alter table public.session_template add column if not exists "user_id" uuid;
alter table public.session_template add column if not exists "updated_at" text;
alter table public.workout_session add column if not exists "block_id" text;
alter table public.workout_session add column if not exists "template_id" text;
alter table public.workout_session add column if not exists "title" text;
alter table public.workout_session add column if not exists "started_at" text;
alter table public.workout_session add column if not exists "ended_at" text;
alter table public.workout_session add column if not exists "status" text;
alter table public.workout_session add column if not exists "user_id" uuid;
alter table public.workout_session add column if not exists "updated_at" text;
alter table public.set_log add column if not exists "session_id" text;
alter table public.set_log add column if not exists "exercise_id" text;
alter table public.set_log add column if not exists "set_index" integer;
alter table public.set_log add column if not exists "reps" integer;
alter table public.set_log add column if not exists "weight_kg" double precision;
alter table public.set_log add column if not exists "done" boolean;
alter table public.set_log add column if not exists "superset_group" integer;
alter table public.set_log add column if not exists "created_at" text;
alter table public.set_log add column if not exists "user_id" uuid;
alter table public.set_log add column if not exists "updated_at" text;
alter table public.week_template add column if not exists "name" text;
alter table public.week_template add column if not exists "data" jsonb;
alter table public.week_template add column if not exists "created_at" text;
alter table public.week_template add column if not exists "user_id" uuid;
alter table public.week_template add column if not exists "updated_at" text;
alter table public.food_entry add column if not exists "date" text;
alter table public.food_entry add column if not exists "meal" text;
alter table public.food_entry add column if not exists "barcode" text;
alter table public.food_entry add column if not exists "name" text;
alter table public.food_entry add column if not exists "amount_g" double precision;
alter table public.food_entry add column if not exists "nutrients" jsonb;
alter table public.food_entry add column if not exists "created_at" text;
alter table public.food_entry add column if not exists "user_id" uuid;
alter table public.food_entry add column if not exists "updated_at" text;
alter table public.notification_pref add column if not exists "category" text;
alter table public.notification_pref add column if not exists "enabled" boolean;
alter table public.notification_pref add column if not exists "quiet_start" text;
alter table public.notification_pref add column if not exists "quiet_end" text;
alter table public.notification_pref add column if not exists "escalation_minutes" integer;
alter table public.notification_pref add column if not exists "digest_time" text;
alter table public.notification_pref add column if not exists "snooze_minutes" integer;
alter table public.notification_pref add column if not exists "user_id" uuid;
alter table public.notification_pref add column if not exists "updated_at" text;
alter table public.body_measurement add column if not exists "date" text;
alter table public.body_measurement add column if not exists "weight_kg" double precision;
alter table public.body_measurement add column if not exists "fat_percent" double precision;
alter table public.body_measurement add column if not exists "muscle_mass_kg" double precision;
alter table public.body_measurement add column if not exists "bone_mass_kg" double precision;
alter table public.body_measurement add column if not exists "bmr_kcal" double precision;
alter table public.body_measurement add column if not exists "created_at" text;
alter table public.body_measurement add column if not exists "user_id" uuid;
alter table public.body_measurement add column if not exists "updated_at" text;
