ALTER TABLE `block` ADD `user_id` text;--> statement-breakpoint
ALTER TABLE `block` ADD `updated_at` text;--> statement-breakpoint
ALTER TABLE `body_measurement` ADD `user_id` text;--> statement-breakpoint
ALTER TABLE `body_measurement` ADD `updated_at` text;--> statement-breakpoint
ALTER TABLE `coach_dismissal` ADD `user_id` text;--> statement-breakpoint
ALTER TABLE `coach_dismissal` ADD `updated_at` text;--> statement-breakpoint
ALTER TABLE `equipment` ADD `user_id` text;--> statement-breakpoint
ALTER TABLE `equipment` ADD `updated_at` text;--> statement-breakpoint
ALTER TABLE `exercise` ADD `user_id` text;--> statement-breakpoint
ALTER TABLE `exercise` ADD `updated_at` text;--> statement-breakpoint
ALTER TABLE `food_entry` ADD `user_id` text;--> statement-breakpoint
ALTER TABLE `food_entry` ADD `updated_at` text;--> statement-breakpoint
ALTER TABLE `notification_pref` ADD `user_id` text;--> statement-breakpoint
ALTER TABLE `notification_pref` ADD `updated_at` text;--> statement-breakpoint
ALTER TABLE `profile` ADD `user_id` text;--> statement-breakpoint
ALTER TABLE `session_template` ADD `user_id` text;--> statement-breakpoint
ALTER TABLE `session_template` ADD `updated_at` text;--> statement-breakpoint
ALTER TABLE `set_log` ADD `user_id` text;--> statement-breakpoint
ALTER TABLE `set_log` ADD `updated_at` text;--> statement-breakpoint
ALTER TABLE `task` ADD `user_id` text;--> statement-breakpoint
ALTER TABLE `task` ADD `updated_at` text;--> statement-breakpoint
ALTER TABLE `week` ADD `user_id` text;--> statement-breakpoint
ALTER TABLE `week` ADD `updated_at` text;--> statement-breakpoint
ALTER TABLE `week_template` ADD `user_id` text;--> statement-breakpoint
ALTER TABLE `week_template` ADD `updated_at` text;--> statement-breakpoint
ALTER TABLE `weekly_structure` ADD `user_id` text;--> statement-breakpoint
ALTER TABLE `weekly_structure` ADD `updated_at` text;--> statement-breakpoint
ALTER TABLE `workout_session` ADD `user_id` text;--> statement-breakpoint
ALTER TABLE `workout_session` ADD `updated_at` text;